#pragma once

#define SETTINGS_FOLDER "Settings"
#define SETTINGS_PATH "Settings/"

#define ASSETS_FOLDER "Assets"
#define ASSETS_PATH "Assets/"
#define MODELS_FOLDER "Assets/Models"
#define MODELS_PATH "Assets/Models/"
#define TEXTURES_FOLDER "Assets/Textures"
#define TEXTURES_PATH "Assets/Textures/"
#define MESHES_FOLDER "Assets/Meshes"
#define MESHES_PATH "Assets/Meshes/"
#define MATERIAL_FOLDER "Assets/Materials"
#define MATERIAL_PATH "Assets/Materials/"
#define ANIMATION_FOLDER "Assets/Animation"
#define ANIMATION_PATH "Assets/Animation/"
#define SCENE_FOLDER "Assets/Scenes"
#define SCENE_PATH "Assets/Scenes/"
#define SCENE_EXT ".chiron"

#define LIB_FOLDER "Lib"
#define LIB_PATH "Lib/"
#define MESHES_LIB_PATH "Lib/Meshes/"
#define MATERIAL_LIB_PATH "Lib/Materials/"
#define ANIMATION_LIB_PATH "Lib/Animation/"
